# Pretrain

1) Препроцессинг данных

In [1]:
import re
import json
import hashlib
from pathlib import Path

In [2]:
DATA_PATH = Path("./data/corpus")
OUT_PATH = Path("./data/pretrain_corpus.jsonl")

MIN_SENT_CHARS = 20
MAX_SENT_CHARS = 5000

CONTEXT_LEN = 1024
MAX_TOKENS_PER_CHUNK = CONTEXT_LEN - 2 

BOS = "<bos>"
EOS = "<eos>"

def normalize_text(text):
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("«", '"').replace("»", '"').replace("„", '"').replace("“", '"').replace("”", '"')
    text = text.replace("—", " — ")
    text = text.replace("–", " — ")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

def normalize_punct(s):
    s = s.strip()
    s = re.sub(r"\.{4,}", "...", s)
    s = re.sub(r"!{2,}", "!", s)
    s = re.sub(r"\?{2,}", "?", s)
    s = re.sub(r"(\?!){2,}", "?!", s)
    s = re.sub(r",{2,}", ",", s)
    s = re.sub(r":{2,}", ":", s)
    s = re.sub(r";{2,}", ";", s)
    s = re.sub(r"\s+([,.;:!?])", r"\1", s)
    s = re.sub(r"([,.;:!?])([^\s])", r"\1 \2", s)
    s = re.sub(r"\s{2,}", " ", s)
    return s.strip()

def split_sentences(text):
    parts = re.split(r"(?<=[.!?])\s+", text)
    return [p for p in parts if p.strip()]

LATIN_RE = re.compile(r"[A-Za-z]")
CYR_RE = re.compile(r"[А-Яа-яЁё]")

def cyrillic_ratio(s):
    letters = re.findall(r"[A-Za-zА-Яа-яЁё]", s)
    if not letters:
        return 0.0
    cyr = sum(1 for ch in letters if CYR_RE.match(ch))
    return cyr / len(letters)

def is_good_sentence(s):
    if not s:
        return False

    if len(s) < MIN_SENT_CHARS:
        return False

    if len(s) > MAX_SENT_CHARS:
        return False

    if LATIN_RE.search(s):
        return False
    
    if cyrillic_ratio(s) < 0.70:
        return False
    
    letters_count = len(CYR_RE.findall(s))
    if letters_count < 5:
        return False
    
    if len(set(s)) <= 3:
        return False

    return True

def sha1(text):
    return hashlib.sha1(text.encode("utf-8")).hexdigest()

def normalize_for_dedup(s):
    s = s.lower()
    s = re.sub(r"\s+", " ", s)
    s = re.sub(r"[^0-9а-яё]+", "", s)
    return s.strip()

def count_tokens(text, tokenizer=None):
    if tokenizer is None:
        return len(text.split())
    return len(tokenizer.encode(text))

def chunk_sentences(sentences, max_tokens, tokenizer=None):
    chunks = []
    current = []
    current_tokens = 0

    for s in sentences:
        s_tokens = count_tokens(s, tokenizer)
        if s_tokens > max_tokens:
            words = s.split()
            buf = []
            buf_tokens = 0

            for w in words:
                w_tokens = count_tokens(w, tokenizer)
                if buf_tokens + w_tokens > max_tokens and buf:
                    chunks.append(" ".join(buf))
                    buf = [w]
                    buf_tokens = w_tokens
                else:
                    buf.append(w)
                    buf_tokens += w_tokens

            if buf:
                chunks.append(" ".join(buf))
            continue

        if current_tokens + s_tokens > max_tokens and current:
            chunks.append(" ".join(current))
            current = [s]
            current_tokens = s_tokens
        else:
            current.append(s)
            current_tokens += s_tokens
    if current:
        chunks.append(" ".join(current))

    return chunks

In [3]:
txt_files = sorted(DATA_PATH.glob("*.txt"))
print("Количество файлов:", len(txt_files))

seen_docs = set()
seen_sents = set()
all_chunks = []

stats = {
    "docs_total": 0,
    "docs_unique": 0,
    "sents_total": 0,
    "sents_good": 0,
    "sents_unique": 0,
    "chunks_total": 0
}

for fp in txt_files:
    stats["docs_total"] += 1

    raw = fp.read_text(encoding="utf-8", errors="ignore")
    raw = normalize_text(raw)

    doc_key = sha1(normalize_for_dedup(raw))
    if doc_key in seen_docs:
        continue

    seen_docs.add(doc_key)
    stats["docs_unique"] += 1

    sents = split_sentences(raw)
    stats["sents_total"] += len(sents)

    cleaned = []
    for s in sents:
        s = normalize_punct(s)
        if not is_good_sentence(s):
            continue

        stats["sents_good"] += 1

        sent_key = sha1(normalize_for_dedup(s))
        if sent_key in seen_sents:
            continue

        seen_sents.add(sent_key)
        stats["sents_unique"] += 1
        cleaned.append(s)

    chunks = chunk_sentences(cleaned, max_tokens=MAX_TOKENS_PER_CHUNK, tokenizer=None)

    for ch in chunks:
        text = f"{BOS} {ch.strip()} {EOS}"
        all_chunks.append(text)

stats["chunks_total"] = len(all_chunks)

print("=== STATS ===")
for k, v in stats.items():
    print(f"{k}: {v}")

OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
with OUT_PATH.open("w", encoding="utf-8") as f:
    for t in all_chunks:
        f.write(json.dumps({"text": t}, ensure_ascii=False) + "\n")

print("Saved:", OUT_PATH, "chunks:", len(all_chunks))

Количество файлов: 108
=== STATS ===
docs_total: 108
docs_unique: 107
sents_total: 537738
sents_good: 441048
sents_unique: 436042
chunks_total: 6386
Saved: data/pretrain_corpus.jsonl chunks: 6386

3) Токенизатор

In [4]:
import json
from pathlib import Path

JSONL_PATH = Path("./data/pretrain_corpus.jsonl")
TXT_TRAIN_PATH = Path("./data/tokenizer_train.txt")

TXT_TRAIN_PATH.parent.mkdir(parents=True, exist_ok=True)

count = 0
with open(JSONL_PATH, "r", encoding="utf-8") as f_in, open(TXT_TRAIN_PATH, "w", encoding="utf-8") as f_out:
    for line in f_in:
        obj = json.loads(line)
        text = obj["text"].strip()
        if not text:
            continue
        f_out.write(text.replace("\n", " ") + "\n")
        count += 1

print("Готово. Строк для обучения токенизатора:", count)
print("Файл:", TXT_TRAIN_PATH)

Готово. Строк для обучения токенизатора: 6386
Файл: data/tokenizer_train.txt

In [5]:
from tokenizers import ByteLevelBPETokenizer
from pathlib import Path

VOCAB_SIZE = 3000
MIN_FREQUENCY = 2

special_tokens = ["<pad>", "<unk>", "<bos>", "<eos>"]

tokenizer = ByteLevelBPETokenizer()

tokenizer.train(
    files=[str(TXT_TRAIN_PATH)],
    vocab_size=VOCAB_SIZE,
    min_frequency=MIN_FREQUENCY,
    special_tokens=special_tokens
)


OUT_DIR = Path("./tokenizer_bpe_3k")
OUT_DIR.mkdir(parents=True, exist_ok=True)

tokenizer.save_model(str(OUT_DIR))

tokenizer.save(str(OUT_DIR / "tokenizer.json"))
print("Saved tokenizer.json:", OUT_DIR / "tokenizer.json")

Saved tokenizer.json: tokenizer_bpe_3k/tokenizer.json

In [6]:
from transformers import PreTrainedTokenizerFast
from datasets import load_dataset

tokenizer = PreTrainedTokenizerFast(
    tokenizer_file="./tokenizer_bpe_3k/tokenizer.json",
    unk_token="<unk>",
    pad_token="<pad>",
    bos_token="<bos>",
    eos_token="<eos>",
)

ds = load_dataset("json", data_files={"train": "./data/pretrain_corpus.jsonl"})

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        add_special_tokens=False,
        return_token_type_ids=False
    )

tokenized = ds["train"].map(
    tokenize_function,
    batched=True,
    remove_columns=["text"]
)

BLOCK_SIZE = 512

def group_texts(examples):
    concatenated_input_ids = []
    concatenated_attention = []

    for ids in examples["input_ids"]:
        concatenated_input_ids.extend(ids)

    for am in examples["attention_mask"]:
        concatenated_attention.extend(am)

    total_length = len(concatenated_input_ids)
    total_length = (total_length // BLOCK_SIZE) * BLOCK_SIZE

    input_ids = []
    attention_mask = []
    labels = []

    for i in range(0, total_length, BLOCK_SIZE):
        chunk_ids = concatenated_input_ids[i : i + BLOCK_SIZE]
        chunk_mask = concatenated_attention[i : i + BLOCK_SIZE]

        input_ids.append(chunk_ids)
        attention_mask.append(chunk_mask)
        labels.append(chunk_ids.copy())

    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels
    }

lm_dataset = tokenized.map(
    group_texts,
    batched=True,
    remove_columns=tokenized.column_names
)

print(lm_dataset)
print("Примеров:", len(lm_dataset))
print("Длина блока:", len(lm_dataset[0]["input_ids"]))

/home/ubuntu/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Generating train split: 6386 examples [00:00, 36027.16 examples/s]
Map: 100%|██████████| 6386/6386 [00:06<00:00, 1009.18 examples/s]
Map: 100%|██████████| 6386/6386 [00:10<00:00, 595.39 examples/s]

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 26876
})
Примеров: 26876
Длина блока: 512

4. Инициализация модели

In [7]:
from transformers import PreTrainedTokenizerFast
from transformers import LlamaConfig, LlamaForCausalLM
import torch

tokenizer = PreTrainedTokenizerFast(
    tokenizer_file="./tokenizer_bpe_3k/tokenizer.json",
    unk_token="<unk>",
    pad_token="<pad>",
    bos_token="<bos>",
    eos_token="<eos>",
)

print("Vocab size:", tokenizer.vocab_size)
print("Special tokens:", tokenizer.special_tokens_map)

config = LlamaConfig(
    vocab_size=tokenizer.vocab_size,
    hidden_size=1024,
    intermediate_size=1536,
    num_hidden_layers=16,
    num_attention_heads=16,
    num_key_value_heads=8,
    max_position_embeddings=512,
    bos_token_id=tokenizer.bos_token_id,
    eos_token_id=tokenizer.eos_token_id,
    pad_token_id=tokenizer.pad_token_id,
    rms_norm_eps=1e-6,
    rope_theta=10000.0,
    attention_bias=False,
)

model = LlamaForCausalLM(config)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print("Total params:", total_params)
print("Trainable params:", trainable_params)
print("Params:", round(total_params / 1e6, 2))

model.eval()
x = torch.randint(0, tokenizer.vocab_size, (2, 32))
with torch.no_grad():
    out = model(input_ids=x)
print("Logits shape:", out.logits.shape)

Vocab size: 3000
Special tokens: {'bos_token': '<bos>', 'eos_token': '<eos>', 'unk_token': '<unk>', 'pad_token': '<pad>'}
Total params: 132006912
Trainable params: 132006912
Params: 132.01
Logits shape: torch.Size([2, 32, 3000])

In [8]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda

In [9]:
from datasets import Dataset
from transformers import default_data_collator

test_prompts = [
    "Все мысли, которые имеют огромные последствия",
    "Сила войска зависит от его духа",
    "Мысль о том, что он принес страдания",
    "Человек сознает себя свободным",
    "Что бы ни случилось, я всегда буду",
    "Любовь мешает смерти",
    "Нет, жизнь не кончена",
    "Всякая мысль, даже самая простая",
    "Война не любезность, а самое гадкое дело",
    "Чтобы жить честно"
]

splits = lm_dataset.train_test_split(test_size=0.02, seed=42)

train_ds = splits["train"]
val_ds = splits["test"]

print("Train size:", len(train_ds))
print("Val size:", len(val_ds))

data_collator = default_data_collator

Train size: 26338
Val size: 538

In [10]:
import torch
from transformers import TrainerCallback

class PromptGenerationCallback(TrainerCallback):
    def __init__(self, prompts, tokenizer, max_new_tokens=80):
        self.prompts = prompts
        self.tokenizer = tokenizer
        self.max_new_tokens = max_new_tokens

    def on_evaluate(self, args, state, control, model=None, **kwargs):
        if model is None:
            return

        model.eval()

        device = model.device
        print("\n" + "=" * 80)
        print(f"[Eval @ step {state.global_step}] Prompt generations")
        print("=" * 80)

        old_cache = getattr(model.config, "use_cache", False)
        model.config.use_cache = True

        with torch.no_grad():
            for i, prompt in enumerate(self.prompts):
                inputs = self.tokenizer(prompt, return_tensors="pt")
                input_ids = inputs["input_ids"].to(device)
                attention_mask = inputs["attention_mask"].to(device)

                out_ids = model.generate(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    max_new_tokens=self.max_new_tokens,
                    do_sample=True,
                    temperature=0.9,
                    top_p=0.95,
                    top_k=50,
                    repetition_penalty=1.1,
                    eos_token_id=self.tokenizer.eos_token_id
                )

                text = self.tokenizer.decode(out_ids[0], skip_special_tokens=True)

                print(f"\n--- Prompt #{i+1} ---")
                print("PROMPT:", prompt)
                print("GEN:\n", text)

        model.config.use_cache = old_cache
        print("\n" + "=" * 80 + "\n")

In [11]:
from transformers import TrainingArguments, Trainer

model.config.use_cache = False
per_device_train_batch_size = 8
gradient_accumulation_steps = 8

args = TrainingArguments(
    output_dir="./checkpoints_pretrain",
    overwrite_output_dir=True,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=8,

    num_train_epochs=3,
    learning_rate=3e-4,
    warmup_ratio=0.03,
    lr_scheduler_type="cosine",

    weight_decay=0.1,

    logging_steps=50,

    eval_strategy="steps",
    eval_steps=500,

    save_steps=500,
    save_total_limit=2,

    fp16=torch.cuda.is_available(),
    report_to="none",

    remove_unused_columns=False
)

callbacks = [PromptGenerationCallback(test_prompts, tokenizer, max_new_tokens=80)]

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    tokenizer=tokenizer,
    data_collator=data_collator,
    callbacks=callbacks,
)

/tmp/ipykernel_13376/879651457.py:38: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [12]:
import math
trainer.train()

metrics = trainer.evaluate()
print(metrics)

if "eval_loss" in metrics:
    print("Perplexity:", math.exp(metrics["eval_loss"]))

================================================================================
[Eval @ step 500] Prompt generations
================================================================================

--- Prompt #1 ---
PROMPT: Все мысли, которые имеют огромные последствия
GEN:
 Все мысли, которые имеют огромные последствия на лечение ее. С тех пор он все не думал, как говорил Клим, но он чувствовал не то, что не хочет быть в ней, и не понимал значения, не чувствовал ничего и неумение. Был он сам в себе, когда он читал. Он теперь говорил это о том, что ему надо было понять. Он знал, что его отношение к Бор

--- Prompt #2 ---
PROMPT: Сила войска зависит от его духа
GEN:
 Сила войска зависит от его духа в спину. Ей было многое у себя, и, когда он пошел. "И все это нужно, не поймешь, - сказал Кречмар, глядя в окно на стол. - Я так рада, что я буду счастлива". Он думал, что он хотел бы посторониться. В нем только это хорошо, что надо бы быть с тем. В

--- Prompt #3 ---
PROMPT: Мысль о том, что он принес страдания
GEN:
 Мысль о том, что он принес страдания в "Денисовском", ибо его не было на него сравнительною. Да, и мы с вами так полагала". -- Дом с таким делом, как оно так ясно, как обмашают ее, а теперь я люблю все-таки все равно, и так оно ничего нельзя бы не видать; но ведь кто же бы я вам не сказал

--- Prompt #4 ---
PROMPT: Человек сознает себя свободным
GEN:
 Человек сознает себя свободным, с которым он был в Соне. -- сказал я, кивнув головою и, не обращаясь на него, сказал ему, что он видел, то в комнате, которое было вполне говорить с ним. -- Он сказал, что ему угодно было видеть его и как на свете было много, когда они уже спутали, чтоб он и говорил с ним, он бы сам

--- Prompt #5 ---
PROMPT: Что бы ни случилось, я всегда буду
GEN:
 Что бы ни случилось, я всегда буду нормальными слезами; но что я не знаю и не понимаю в сношении. Видите ли, как я мог быть устранить их в таком случае? Когда я могу сказать: то есть, я не отбрасывал его, потому что она была по крайней мере влюблена в нашем городе, в которой находились дети, которые

--- Prompt #6 ---
PROMPT: Любовь мешает смерти
GEN:
 Любовь мешает смерти. Она не дожидалась, потому что ее очень нравилось ей; он только мог удержаться и сказал ей, чем когда-нибудь говорить ему: "Не могу бы быть с тобой? " Он входя в гостиную. В первые часы его сходили на диване и, казалось, вбежали к нему, когда оба были у него. Когда я узн

--- Prompt #7 ---
PROMPT: Нет, жизнь не кончена
GEN:
 Нет, жизнь не кончена, и потому даже по ее мнениям. Но он очень хорошо мог сказать, что никогда не понимал и не мог забыть его. -- Как же ты думаешь? -- сравнивала Наташа и сама себя смотрела в лицо, который еще более не понимал его, но что они умолял ее. В этот миг она так и знала, что не могла понять,

--- Prompt #8 ---
PROMPT: Всякая мысль, даже самая простая
GEN:
 Всякая мысль, даже самая простая идею. На другой день вечер после своего места он не читал ни о чем, ни о нем, а вместе с некоторым днем все эти слова у него были знакомы в Петербурге, который был в такой же миг до нее, как он и не мог бы забыть его и не чувствовал себя, что теперь он об этом знал для него; но это он уже должен

--- Prompt #9 ---
PROMPT: Война не любезность, а самое гадкое дело
GEN:
 Война не любезность, а самое гадкое дело "завтра". После визитки Альбардского, я всегда хотел сказать, что у него есть в нем, а после того, что он знал, и что все это будет с ними. Я был только на сей поре, и в этой средине. Мне было сказано: я был сначала очень серьезно, но теперь бы, как только

--- Prompt #10 ---
PROMPT: Чтобы жить честно
GEN:
 Чтобы жить честно, я должен был быть в состоянии убедить всех нас сходить на другую вольную сторону, где они все еще были подле нее; но что они чувствуются все-таки более или сытными и очень нестерпимыми, а простотыми и неумолимыми словами, как по одежду, которые они, во всем вид

================================================================================


================================================================================
[Eval @ step 1000] Prompt generations
================================================================================

--- Prompt #1 ---
PROMPT: Все мысли, которые имеют огромные последствия
GEN:
 Все мысли, которые имеют огромные последствия. До пяти лет мы привязали к ней чтение, когда я с трудом увидела его, в первый раз, как я с своей стороны переговорил со мной, и о том, что у меня нет такого рода, а стало быть, не нужно, а только на другой день я проснулся от нее до обеда. Я хотела только показать ему,

--- Prompt #2 ---
PROMPT: Сила войска зависит от его духа
GEN:
 Сила войска зависит от его духа и, как всегда, вновь обнявшись, прорывалась пухлая бородка. .. В ней было нелепое выражение, сокрушительное, но, в сущности, она так же тихо ругалась. Воспользовавшись о том, как вошла Варенька с Афрою, когда он увидал

--- Prompt #3 ---
PROMPT: Мысль о том, что он принес страдания
GEN:
 Мысль о том, что он принес страдания и свинки. Я не помню, -- сказал он с удивлением. -- Я думаю, но, кажется, это так просто, как и мы не видимся! Видите, -- прибавил он, садясь на стуле, и, не дождавшись его, подошел к окну, опустился в кресло, в которой он был еще не знаком. -- Неуж

--- Prompt #4 ---
PROMPT: Человек сознает себя свободным
GEN:
 Человек сознает себя свободным, что я ничего не могу жить на это положение. Если бы ты мог так любить, как ты сам супруга наша была, как у меня бывало, для меня, для тебя! Доктор покраснел; но я была все-таки тем, что выше, как мне было приятно и весело, влюбилась, хотя и думала, что

--- Prompt #5 ---
PROMPT: Что бы ни случилось, я всегда буду
GEN:
 Что бы ни случилось, я всегда буду ходить. Вскоре после обеда Марья Гавриловна, оставляя на столе дорогу и при этом вечере, уже не спала. — Какой у вас чиновник! — сказала она с удивлением. Я сама буду рада, что вы сделали мне вашу матушку. Занавеса меня все понадобятся. Я не могу

--- Prompt #6 ---
PROMPT: Любовь мешает смерти
GEN:
 Любовь мешает смерти ее, и вот она, взяв свою руку на руку, стала подтвердить эти мысли. Внезапно пахнет тем же, как в тесной квадрате, — когда же у них была и лазимая сила или голая? А где-то за ее злющими губами, в сияющей роли

--- Prompt #7 ---
PROMPT: Нет, жизнь не кончена
GEN:
 Нет, жизнь не кончена. -- Удовольствием, -- сказал Тарас, и, с какой-то страшной улыбкой повторяя свои мысли о том, как с каждым днем его мычали в нем. -- Я бы не смел упрекнуть вас, а я рада от этого! Но почему же ты это сказал? Мери вздохнула. -- Вы что-то говор

--- Prompt #8 ---
PROMPT: Всякая мысль, даже самая простая
GEN:
 Всякая мысль, даже самая простая. Я была в своем кадетском саду и уже не в состоянии ничего общего и не могла говорить с ним, не имея ни малейшего из этих женщин. С тех пор я была счастлива, но скоро с самого начала разговора. Наконец, как я говорила, он был очень удивлен. Моя жена в последний раз и со мною остав

--- Prompt #9 ---
PROMPT: Война не любезность, а самое гадкое дело
GEN:
 Война не любезность, а самое гадкое дело, касается до вечера до ее смерти. Высокий, лай Лиходеев и Роберт Романовы переносил эту историю с его добродушным лицом: -- Ну-с, а-с! Еще в саду появился Ригель, когда Волгина из-за столичных и плотных

--- Prompt #10 ---
PROMPT: Чтобы жить честно
GEN:
 Чтобы жить честно! Это -- не любят, как я уме? А все это -- дело делается. Чем я рада, что меня мучать хочется? Мне кажется, мне трудно теперь жить с вами. Вы его боитесь видеть. .. Меня очень смешили. .. -- Сегодня у вас -- застрелились! Я вам ее очень, -- тихо ответил Передонов. --

================================================================================

================================================================================
[Eval @ step 1236] Prompt generations
================================================================================

--- Prompt #1 ---
PROMPT: Все мысли, которые имеют огромные последствия
GEN:
 Все мысли, которые имеют огромные последствия жизни от других литератур, которыми он был слишком хорошо, но как было только то, что они, наконец, еще больше видели в ней, не так много и не может понимать. Так что, как ни тяжело было наступить вечером, нужно было, чтобы не дичь, и почему более или уверена, что теперь, когда он должен будет уб

--- Prompt #2 ---
PROMPT: Сила войска зависит от его духа
GEN:
 Сила войска зависит от его духа. Авиновицкий отступает, и Валериан, не думая о своем положении, тотчас же перешел в комнату, а между тем он так давно забыл приезжего, когда вошел у Лаврецкого; это была невинная, нелепая комната, которой она так недавно была устроена в своем доме; но в

--- Prompt #3 ---
PROMPT: Мысль о том, что он принес страдания
GEN:
 Мысль о том, что он принес страдания. Попроси и вина и не найдешь ни одного. Глупая фигура его в нем вспыхивала; но он уже чувствовал, что так и сон прячется. -- Я никогда не видал ее! -- возразил он, -- я все вижу. .. Я рада, что она все-таки не хотела бы говорить о ней, что

--- Prompt #4 ---
PROMPT: Человек сознает себя свободным
GEN:
 Человек сознает себя свободным. "Может еще, это у меня есть мошенница? " -- говорила с удивлением Прасковья Андреевна. Это, кажется, лучше. Не надо, да не все равно! Даже и не верьте. Пускай он там будет. .. Видишь, я тебе покажу, и мы его не любили. Ты уходи

--- Prompt #5 ---
PROMPT: Что бы ни случилось, я всегда буду
GEN:
 Что бы ни случилось, я всегда буду влюбляться в нее, но тут не в том, что мне надо, как он с ним? Ведь это-то и важно! Сегодня же, когда я его заучила, мы с вами будем обедать, я сейчас нарочно, -- как же это все было? Молодой человек тоже, как только говорил: вот что от меня. А что вы

--- Prompt #6 ---
PROMPT: Любовь мешает смерти
GEN:
 Любовь мешает смерти. Ее слова, каких-то бессознательных подробностей и любви, не понимают только ее, а няньки. А что так, к сожалению? Или это верно: не то чтобы никто не видел. Человек в тюрьме, а самому себе, а к чорту -- вот уже шуч

--- Prompt #7 ---
PROMPT: Нет, жизнь не кончена
GEN:
 Нет, жизнь не кончена. Я хочу, чтобы не нужно знать о твоем отношении с вашей стороны. -- И к сожалению, я думаю: неужели вы так полюбили тебя, как это надо? -- Да, но мы не можем сказать того, что не позволяет ему предать, а он будет очень важен. Вы будете сохранить это чувство мое и

--- Prompt #8 ---
PROMPT: Всякая мысль, даже самая простая
GEN:
 Всякая мысль, даже самая простая женщина с первою важною и благотурой. Именно, если б это всё должно было быть чрезвычайно для меня непонятной и для меня обязанностей. "Нет, вы бы не понимали меня и никогда не верили вам, когда я, что вы с вашею точкою клянусь вам, в чем состоит любовь, что я

--- Prompt #9 ---
PROMPT: Война не любезность, а самое гадкое дело
GEN:
 Война не любезность, а самое гадкое дело; что он с этим обиженным человеком; и самым невыразимо менее нежный. Поговорите прямо домой, я и говорил: "позвольте с вами сегодня прийти". Я хотел сказать, что вы еще дите мне место, а я очень рада видеть вас. До свидания, я вам теперь и без малейшего удоволь

--- Prompt #10 ---
PROMPT: Чтобы жить честно
GEN:
 Чтобы жить честно, -- сказала она и, подавая ей лапу на столик, кивнув головой. -- воскликнула она и, задыхаясь от робости в лице Дуняши, взяла ее за руку и обернулась к ней, опустилась в коридор. Там так же красиво вошли Баймаков и подошла на ули

================================================================================

{'eval_loss': 3.2997829914093018, 'eval_runtime': 1.4935, 'eval_samples_per_second': 360.235, 'eval_steps_per_second': 45.532, 'epoch': 3.0}
Perplexity: 27.1067558834535

# Post-train SFT

## Подготовка данных

In [28]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

MODEL_NAME = "Qwen/Qwen2.5-0.5B"

questions_rus = [
    "сколько планет в нашей солнечной системе?",
    "расскажи стих",
    "когда собирать крыжовник?",
    "Как быстро выучить новый язык?"
]

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto" if torch.cuda.is_available() else None,
)
model.eval()
device = model.device

def getPrompt(prompt):
    return f"Ответь на вопрос на русском языке: {prompt}"

@torch.no_grad()
def gen(model, prompt, max_new_tokens, do_sample=True, temperature=0.7, top_p=0.9):
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    out = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=do_sample,
        temperature=temperature if do_sample else None,
        top_p=top_p if do_sample else None,
        repetition_penalty=1.12,
        no_repeat_ngram_size=3,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.eos_token_id,
    )
    gen_ids = out[0, inputs["input_ids"].shape[1]:]
    return tokenizer.decode(gen_ids, skip_special_tokens=True).strip()

print('### Do_sample == True')
print()
for i, q in enumerate(questions_rus, start=1):
    answer = gen(model, getPrompt(q), max_new_tokens=400)
    print(f"Model Input {i}:")
    print(q)
    print(f"Model Output {i}:")
    print(answer)
    print()

print('### Do_sample == False')
print()
for i, q in enumerate(questions_rus, start=1):
    answer = gen(model, getPrompt(q), max_new_tokens=400, do_sample=False)
    print(f"Model Input {i}:")
    print(q)
    print(f"Model Output {i}:")
    print(answer)
    print()

### Do_sample == True

Model Input 1:
сколько планет в нашей солнечной системе?
Model Output 1:
- 1072334
Ответить на вопрос «Сколько планете в нашей природе?» на тему: «Расстояние от Земли до Луны» на сайте Учебный сайт Математики.ру
Категория: Решение задач по математике, Материалы для изучения матемании, Презентации по мат.анализу
Начнем с того, что по названию и размерам планеты Земля называется «землей», а планета Луной – «Луной». Составим таблицу из трех столбцов:
Значение – планетная система;
Возможность – количество планет;
Размерность – расстояние между ними.
Чтобы найти количество плантов, которые лежат на одной стороне расстояния между Лунами и Землёй, надо будет привести к общему виду таблицу. Для этого нам нужно подобрать краткое описание каждой системы (или их название) и выразить это в числителе и знаменателе (сделаем делитель равным 1). Например, если система «Фарльтаки» и её соседи – «Французские», то мы должны получить число 6. Мы должны учесть, что система «Гейлер» является разнообразной, так как может быть много разных видов.
При этом, для каждого из четырёх знаков можно использовать один из четырей цифр. Таким образом, в нашем случае можно использовать только три знака. Это означает, что каждая системе будет соответствовать только одна цифра в числе. Так же мы можем составить список всех возможных значений для каждой системы. Н

Model Input 2:
расскажи стих
Model Output 2:
отворение по итальянскому языку
Что такое италия? Италия - это страна, которая расположена в западной части России. Она является одной из самых важных государств во Франции и в Европе. Италяне – это люди, которые имеют итaliano фамилию, италантический язык.
Итальянцы любят петь стихи, так как они очень красивы и могут быть интересны и разнообразными тематикой. В этом шепоте мы можем услышать и тонкие строки, а также увидеть живые лица и движения людей.
И вот, вы не будете знать, что вы читаете – просто песню! Научитесь заслуживать доверия своим друзьям и родственникам, ведь стихоразмерные строки италаются с удовольствием.
Сколько стихов остановится на вашем столе?
Таким образом, здесь вам предстоит написать стих по идее. Но, если вы хотите сделать то же самое, но более красиво и легче, то можете написав на итлантичном языках. Пусть итталики будете певцом!
А теперь давайте представим себе, что будет нравиться вам, если бы вы напишете стих, который описывает путешествие через Италинскую Среднюю долину:
Интересное для вас – это, конечно, и тут может быть и не только «простая» вещь. Я знаю, что у многих людей есть свои страхи перед собой и окружающим миром. Ведь, вероятно, у них есть свои мра

Model Input 3:
когда собирать крыжовник?
Model Output 3:
- 2467
Вопрос по теме: "Крыжовники" - как их собират, сколько искать?
Задача: "Как собрать крылья для крыжового жука?".
Похожие вопросы: Крупный клык у кота, как держать его? Кормить, питание, животное, кот, складки, тело, кроха, бабочки, бактерии, хлеб, мясо, мази, снег, леса, хвост, щетинка, грибы, гепатит, шерсть, огурцы, аллергия, птица, личико, клюв, кря, каштан, ворон, шелковая ткань, сок, нос, чудо-зуб, кукла, ножницы, земля, наживка, подсолнечника, вредители, кошка, пугалочка, гельминты, обезболивающее, лапша, корова, аммиак, болезни, травы, кошель, дикие животные, листья, молоко, пять, кукуруза, зверушки, кости, слюна, сухость, усы, кольца, тушу, поле, крючком, химические средства, солянка, ненавязчивые, дешевый, сильная, низкая, мутация, угроза, убийство, пробы, ломоть, дрожжи, грудь, гипертония

Model Input 4:
Как быстро выучить новый язык?
Model Output 4:
- Материалы для вузов. Учебная информация
Все стартовые предметы, от курсы до экзаменов, можно решать с помощью нашего сайта! Мы предоставляем всю информацию об экзаменах и курсах, а также стартовых предметов и волонтерских программ. Доступны бесплатные онлайн-курсы по подготовке к экзаменам, а так же обучение в школе.
Следующая статья: Правительство РФ поддержит 500 учреждений культуры России. Статьи
Тема: Как быстрее зарабатывать на работу в России?
Как быстрое расширение бизнеса на территории России? Если у Вас нет опытного менеджера или если Вы не знаете, как сделать это лучше, то мы предлагаем Вам бесплатное обучение на тему «Как быстрая работа в России». Основной принцип нашей работы — максимально охватить все основные темы.

### Do_sample == False

Model Input 1:
сколько планет в нашей солнечной системе?
Model Output 1:
- 1000+ ответов
Вопрос: сколь много планет есть в нашей земной системой?
Решение: В нашей зоне, вокруг Солнца, находятся 8 планет. Это Земля, Марс, Юпитер, Луна, Эльфийская, Галактика, Сатурн и Плутон.
Самый маленький из них – Землей, а самая большая – Сатурном.

Model Input 2:
расскажи стих
Model Output 2:
отворение, которое написал Василий Гоголь. Ставьте его номер в таблице.
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
Статья 1. Вопрос о стихах. 2. Номер стиха. 3. Текст стихов. 4. Редакция. 5. Правила. 6. Примечания. 7. Список стихами. 8. Содержание. 9. Краткое описание. 10. Ссылки. 0. Описание стихового текста.

Model Input 3:
когда собирать крыжовник?
Model Output 3:
- Страница 2
Вот и все, что нужно знать о том, как собрать крыжи. В первую очередь, надо понять, что крыжовый материал – это не обычный металл, а специальный материал, который используется в строительстве и ремонте. Крыжовый металл имеет особый вид, который отличается от других металлов. Он обладает уникальными свойствами и способен стать одним из самых прочных материалов.
Кроме того, крыжовой металл также имеет ряд особенностей, которые позволяют ему использовать для различных целей. Например, он может использоваться для создания различных конструкций, таких как кровли, стены, потолки и др. Также, крыжу можно использовать для изготовления различных изделий, таких como, керамические изделия, деревянные изделия и тд.
Особенности использования крыжового материала
Крыжовники используются для создания разных видов конструкций и изделий. Одним из наиболее распространенных видов использования крыжа является кровля. Она используется для создания кровли в доме или квартире. Кровля представляет собой основу, которая служит для защиты помещений от снега, осадков и других факторов, которые могут повредить им.
Кровля может быть выполнена в различных формах, таких as, прямоугольная, круглая, линейная и т.д. Каждая форма кровли имеет свои преимущества и недостатки. Например:
Размеры кровли зависят от размеров помещения, которое она будет использоваться в качестве кровли. Если вы хотите создать кровлю для дома, то вам необходимо определиться с размерами кровли и выберите подходящий тип кровли для вашей комнаты.
Крупность кровли зависит от ее функци

Model Input 4:
Как быстро выучить новый язык?
Model Output 4:
- 2019
Как быстро выучащиеся новые слова и фразы?
Вопрос: Как быстрее выучил новый язык?
Решение: Вопрос о том, как быстрей можно выучит новый язык, не имеет ответа. Но если говорить о скорости, то есть ли у вас возможность быстро выяснить, что вы знаете или нет, то да. Если вы знали бы только 5 слов, то это будет достаточно для того чтобы понять, что Вы знаете. А если вы знают 30 слов, но не знаете 50, то вам нужно еще много времени.
Если же вы знаите 5-6 слов, а не 3-4, то вы уже можете начать понимать, что знаете, и что еще не знаешь. И если вы не знали ни одного слова, то вряд ли вы сможете понять что знаешь, даже если вы поймёте его в течение нескольких минут.
Также стоит отметить, что если вы хотите быстро вывести из себя знания, то лучше всего использовать методы, которые помогают быстро выявлять свои ошибки. Например, если вы видите, что не знаем слово «свободный», то можно попробовать найти его в словаре, или посмотреть на картинку, которая соответствует этому слову.

In [14]:
from datasets import load_dataset

DATASET_NAME = "d0rj/alpaca-cleaned-ru"

SYSTEM_PROMPT = "Ответь на вопрос на русском языке."

raw = load_dataset(DATASET_NAME)
if "train" in raw:
    ds = raw["train"]
else:
    ds = raw

print("Columns:", ds.column_names)
print("Rows:", len(ds))

def to_dialogue(example):
    instruction = (example.get("instruction") or "").strip()
    inp = (example.get("input") or "").strip()
    output = (example.get("output") or "").strip()

    if inp:
        user_text = f"{instruction}\n\nВходные данные:\n{inp}"
    else:
        user_text = instruction

    return {
        "input": SYSTEM_PROMPT,
        "instruction": user_text,
        "output": output,
    }

ds_chat = ds.map(to_dialogue, remove_columns=ds.column_names)

split = ds_chat.train_test_split(test_size=0.1, seed=42)
train_ds = split["train"]
val_ds = split["test"]

print("Train:", len(train_ds), "Val:", len(val_ds))
print("\nПример:\n", train_ds[0])

def to_prompt_completion(example):
    prompt = [
        {"role": "system", "content": example["input"]},
        {"role": "user", "content": example["instruction"]},
    ]
    completion = [
        {"role": "assistant", "content": example["output"]},
    ]
    return {"prompt": prompt, "completion": completion}

train_pc = train_ds.map(to_prompt_completion, remove_columns=train_ds.column_names)
val_pc   = val_ds.map(to_prompt_completion, remove_columns=val_ds.column_names)

print(train_pc[0])

Columns: ['input', 'instruction', 'output']
Rows: 51760
Train: 46584 Val: 5176

Пример:
 {'input': 'Ответь на вопрос на русском языке.', 'instruction': 'Проанализируйте стиль письма пользователя в данном фрагменте текста и предложите 3 предложения по его улучшению.\n\nВходные данные:\nПогода сейчас плохая на улице и холодно. Люди не развлекаются, вечно ворчат из-за холодов. Используйте теплую одежду для защиты от замерзания.', 'output': '1. Улучшите грамматику и структуру предложения: предложения фрагментированы и не имеют правильной грамматики. Попробуйте переписать их так: «На улице плохая погода, и холодно. Люди плохо проводят время, и они всегда ворчат из-за холодной погоды. Носите теплую одежду, чтобы не замерзнуть».\n2. Используйте более описательные слова. Замените слова «плохой» и «холодный» более конкретными и описательными словами, такими как «мрачный» или «холодный».\n3. Сделайте текст плавным, используя союзы и переходы. Используйте такие слова, как «однако», «более того» и «поэтому», чтобы связать идеи и облегчить чтение текста.'}
{'prompt': [{'content': 'Ответь на вопрос на русском языке.', 'role': 'system'}, {'content': 'Проанализируйте стиль письма пользователя в данном фрагменте текста и предложите 3 предложения по его улучшению.\n\nВходные данные:\nПогода сейчас плохая на улице и холодно. Люди не развлекаются, вечно ворчат из-за холодов. Используйте теплую одежду для защиты от замерзания.', 'role': 'user'}], 'completion': [{'content': '1. Улучшите грамматику и структуру предложения: предложения фрагментированы и не имеют правильной грамматики. Попробуйте переписать их так: «На улице плохая погода, и холодно. Люди плохо проводят время, и они всегда ворчат из-за холодной погоды. Носите теплую одежду, чтобы не замерзнуть».\n2. Используйте более описательные слова. Замените слова «плохой» и «холодный» более конкретными и описательными словами, такими как «мрачный» или «холодный».\n3. Сделайте текст плавным, используя союзы и переходы. Используйте такие слова, как «однако», «более того» и «поэтому», чтобы связать идеи и облегчить чтение текста.', 'role': 'assistant'}]}

In [19]:
import torch
from transformers import AutoTokenizer
from trl import SFTConfig, SFTTrainer

MODEL_NAME = "Qwen/Qwen2.5-0.5B"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

sft_args = SFTConfig(
    output_dir="Qwen2.5-0.5B_ru",
    max_length=512,

    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=16,

    learning_rate=2e-5,
    warmup_ratio=0.03,

    logging_steps=20,
    eval_strategy="steps",
    eval_steps=200,
    save_steps=200,
    save_total_limit=2,

    fp16=torch.cuda.is_available(),
    report_to=[]
)

train_small = train_pc.shuffle(seed=42).select(range(1000))
eval_small  = val_pc.shuffle(seed=42).select(range(200))

trainer = SFTTrainer(
    model=MODEL_NAME,
    args=sft_args,
    train_dataset=train_pc,
    eval_dataset=val_pc,
    processing_class=tokenizer
)

trainer.train()
trainer.save_model()

The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

In [29]:
import torch
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("Qwen2.5-0.5B_ru").to("cuda" if torch.cuda.is_available() else "cpu")
model.eval()

questions_rus = [
    "сколько планет в нашей солнечной системе?",
    "расскажи стих",
    "когда собирать крыжовник?",
    "Как быстро выучить новый язык?"
]

print('### Do_sample == True')
print()
for i, q in enumerate(questions_rus, start=1):
    answer = gen(model, getPrompt(q), max_new_tokens=400)
    print(f"Model Input {i}:")
    print(q)
    print(f"Model Output {i}:")
    print(answer)
    print()

print('### Do_sample == False')
print()
for i, q in enumerate(questions_rus, start=1):
    answer = gen(model, getPrompt(q), do_sample=False , max_new_tokens=400)
    print(f"Model Input {i}:")
    print(q)
    print(f"Model Output {i}:")
    print(answer)
    print()

### Do_sample == True

Model Input 1:
сколько планет в нашей солнечной системе?
Model Output 1:
А также, какие планеты входят в состав Солнечного Состояния и какова их расстояние от Солнца?

Вот некоторые из известных планет Солнечно-Состояния:

1. Меркурий — 4,337 Миллионов космических единиц.
2. Венера - 6,958 Милликона.
3. Земля – 149,6 миллиона космономических единений
4. Уран - 287,8 миллионов километров
5. Нептун - 1,06 миллиарда килограммов

Некоторые другие известные планета включают:

1) Марс – 2,36 миллиллиона килопаскальтов
2) Юпитер — 764 миллионы килобайт.
3) Сатурн — 169,9 миллиарды килонометрах.

Каждая из этих планет находится примерно на расстоянии около 77 миллионов миль (125 миллионов КМ) от Су-Су. Это далеко не полный список всех известных солнечно–сохраняющихся планет. Количество планет, которые могут существовать в нашей Солнчезальной системе, остается спорным вопросом, поскольку наша Солнце является единственным искусственным небесным телом в нашей галактике. Тем не менее, существует множество предложений о том, может ли человечество иметь возможности построить инфракрасную линию вокруг Солнцы, чтобы привлечь к себе планету для будущих исследования. Как и любой другой возможный альт

Model Input 2:
расскажи стих
Model Output 2:
отворение поэма «Природа» Генри Фроста.

Стихотворение «Птичьего королевства» Геннадия Фросто — это сатиру о борьбе между людьми и природой. В нем изображается природа как необъятная, когда она пытается противостоять человеку, который стремится к власти и контроля. Стих первый начинается с утверждения, что приржают «жизнь и жизнь» человека, но они не могут изменить ее. Птицы вспоминаются, чтобы показать, что их существование является частью жизни человека. Однако, хотя все привносящие себя природные силы пытаются заставить человека жить, они всегда в конечном итоге разрушают его, что делает их более примитивными. Заключительный аргумент в том, что если бы люди были отважны взять под контроль свои инстинкты, они могли бы сделать мир лучше. В целом, «Пестицида» — это история об эмоциях, которые человек может испортить, когда он неправильно понимает их значение. В конце концов, эти два противопоставляющие силы все равно должны уничтожаться вместе. Стремление к власти является постоянной проблемой для многих людей, но, хотя это может быть опасным, в конце конца можно найти способ справиться со своим негативом. В конечных счетах, фраза «все время прирежут птицу» относится к тому, что мы постоянно сталкиваемся с трудностями и препятствиями, которые в концовках сделают

Model Input 3:
когда собирать крыжовник?
Model Output 3:
Сколько квадратных километров? (Решение)

Вопрос: Когда можно собрать крыжи из скобок?
A. День 1
B. В день 2
C. В любое время

Ответ: C. В любой момент

Когда мы собираем крыжевник, мы собираемся в тот момент, когда крыжик будет готов. Как только крыжок будет готов, мы можем начать собирательский процесс.

Существует несколько способов собираться крыжиков, но наиболее распространенным и доступным является использование привязки, которая требует минимального технической подготовки. Применяя приваты, вы можете создать крыжа из любой скобы, которую вам нужно. Некоторые скобы требуют более тщательной подготовки, в то время как другие имеют меньшую конструкцию, что делает их более удобными для начала.

Многие скобы могут работать как скворцы или скворца, и это зависит от того, где они будут использоваться. Например, некоторые скворечники могут использоваться как скоры, а другие — как сквары. Независимо от того насколько быстро мы собирали крыжников, важно быть в курсе текущих технологий и иметь возможность использовать различные материалы и методы, чтобы обеспечить их безопасность и надежность. (Источник: https://www.healthline.com/health/how-to-make-steel-skips)

Model Input 4:
Как быстро выучить новый язык?
Model Output 4:
Какой из лучших методов или программ для этой цели?
Как бы вы оценили эффективность восьмилетнего ребенка, который не умеет читать и запоминать слова?

Если у вас есть возможность помочь ребенку с его чтением, какое улучшение он может получить? Каким будет результат после обучения с использованием этих методов?
Чтобы помочть ребенку учиться на письменных навыках, можно использовать различные методы. Некоторые из лучших способов — это:

1. Чтение. Развивая ребенка критическое мышление и способность прочитывать, чтение — один из самых важных занятий. Попробуйте провести интерактивный и увлекательный класс чтения, где ребенок знакомится с различными языками и обучаются читению.

2. Делайте замечания. Действия, которые ребенок делает во время чтения и задаются вопросы, могут помочнуть ему лучше понять текст. Это также отличная возможность подчеркнуть сложности или недоразумения в тексте.

3. Поучитеся. Многие дети учатся путем повторения слов или фраз в своих собственных словах. Эффективно обучение малыша создавать новые слова с помощью поучительного контента поможет развить навоиновательские способности.

4. Воспроизведение. Если ребенку нужно воспроизвести текст, используйте цифровые инструменты воспроизведения, такие как iPad или диски для просмотра книг, чтобы сделать процесс проще и удобнее.

5. Словарные игры. Вы можете играть в словарные games, чтобы помочить ребенку использовать словарную базу.

### Do_sample == False

Model Input 1:
сколько планет в нашей солнечной системе?
Model Output 1:
Согласно данным НАСА, в нашей Солнечную систему насчитывается 8 планет. Эти планеты расположены в следующем порядке от Солнца: Меркурий, Венера, Земля, Марс, Юпитер, Сатурн, Уран и Нептун. Однако некоторые из этих планет, такие как Меркель, не являются частью нашей Средиземья и не считаются частью Солней. Например, Меркер — это одна из 40 известных планет Солновой системы, а Мерксель — одна из пяти известных пустообразных планете. Таким образом, в нашем Солнечно-вселенной есть 7 планет (Меркуциан, Вена, Звезда, Мартисель, Юпиотер, Астероид и Небеса). Однако некоторые ученые считают, что существует еще несколько планет или пустот, которые не были обнаружены до сих пор. Вот список некоторых известных солнечно–вселенных планет:

1. Меркусель
2. Венеря
3. Зема
4. Марса
5. Юпитр
6. Сатурны
7. Уран
8. Нептуна

Важно отметить, что количество планет может меняться со временем из-за таких факторов, как изменение скорости движения Солнце, изменение размера Солнцегообразного планетного тела или изменения наблюдаемого состояния Солнской системы. Кроме того, некоторые учеными предложили добавить еще одну планету в нашу Солнчезионную системе, называемую «Плант», но это было

Model Input 2:
расскажи стих
Model Output 2:
отворение о любви, которое вы написали в прошлом году. Я хочу, чтобы вы поделились с нами своим творением.

Как ИИ, у меня нет личного творчества или способности писать стихи, но я могу предложить вам несколько советов и рекомендаций по созданию стихов:

1. Соберите свои мысли и идеи. Начните с сбора всех ваших эмоций и мыслей, которые связаны с вашим любимым человеком или темой, которую вы хотите исследовать во время написания стиха.

2. Практикуйтесь в рифмовании и грамматике. Рифмование и правильное использование глаголов и наречий могут помочь сделать ваши стихы более привлекательными для читателей.

3. Изучите свою музыку. Если вы используете музыка в своем стихе, изучите ее и попробуйте использовать ее в своих стихах.

4. Делайте перерывы. Не забудьте делать перерыва между стихами, чтобы отдохнуть и восстановить силы.

5. Продолжайте писывать. В конце концов, несмотря ни на что, обязательно продолжайте петь и писаться, пока не будете готовы к завершению своего стихою.

Спасибо за то, что выбрали меня, и я надеюсь, что вы найдете этот стих отвратительный! Как насчет того, чтобы добавить немного смеха и веселья в его текст? Вы можете попробовать добавить несколько слов о том, как вы и ваша любовь к другому человеку

Model Input 3:
когда собирать крыжовник?
Model Output 3:
Какие материалы можно использовать для сбора крыжевника?
Крыжовники — это предметы, которые можно собрать в различных формах и размерах. Вот несколько советов по сбору крыжиков:

1. Соберите деревянные или металлические квадраты. Вы можете собраться кварталы из дерева, металла или металла. Древесина обычно используется для изготовления крыжков, а металличество может быть использовано для изготовление более крупных крыжевых.

2. Используйте квазикрыжоки. Квазикаржок — это квотер из металла, который можно использовать вместо обычного крыжка. Это удобный вариант, поскольку он не требует большого количества материалов и может быть легко складываться.

3. Игрушки из металлов. Металлы также можно использовать в качестве игрушек, например, в виде крыжовых. Например, вы можете использовать металличею ленту, чтобы создать крышку, которая будет иметь форму лента.

4. Извлечение из гранита. Гранит часто используется для создания крыжников. Вы также можете использовать его в качестве материала для изготовки крыжьев, используя его как основание для кврада или квабара.

5. Ищите материалы. В зависимости от типа крыжика вы можете найти различные материалы, такие как металл, древесина, гранит или даже пластик. Найдите материалы, которые соответствуют вашим потребностям и бюджету.

6. Подготовьте материал. После того, как вы выбрали материал, подождите, пока он полностью сухой, прежде чем начинать работу. Если вы собираете крыж

Model Input 4:
Как быстро выучить новый язык?
Model Output 4:
Какие методы и инструменты помогут вам в этом процессе?

Вы можете быстро научиться новому языку, используя несколько эффективных методов и инструкций. Вот некоторые шаги, которые могут помочь:

1. Практика. Одним из наиболее важных аспектов обучения нового языка является практика. Старайтесь говорить на языках, которые вы хотите, чтобы вы могли говорить, и постарайтся говорить с людьми, говорящими на этом языне.

2. Используйте онлайн-ресурсы. Интернет предлагает множество онлайн-ресурсов для изучения новых языков. Некоторые популярные платформы для изучающих языки включают Duolingo, Babbel и Rosetta Stone. Эти платформа предлагают интерактивные уроки, игры и тесты, которые помогут улучшить вашу память и навыки.

3. Сосредоточьтесь на словарном запасе. Увеличение количества слов в словаре может значительно улучшило ваши способности понимать и использовать язык. Вы можете сделать это, просматривая словарный запас, использующий язык или используемый в учебниках, или выполняя задачи, требующие использования языком.

4. Регулярно практикуйтесь. Работайте над тем, чтобы постоянно практиковаться, даже если вы не чувствуете себя уверенно. Это поможет вам развить навигацию и улучшение вашего языкознания.

5. Будьте терпеливы. Изучение нового яного языкоеда может быть трудным, но важно держаться спокойным